version: "3"
services:
  web:
    image: nginx:alpine
    container_name: web
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./logs:/var/log/nginx
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    image: searazazel/firewall
    container_name: app
    ports:
      - ${LARAVEL_SERVER_PORT}:8000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./logs:/var/log/php

  db:
    image: mysql:8.0.16
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80

volumes:
  db-data:
    driver: local
